app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'

urlpatterns = [
    path('inicio/', views.inicio),
    path('home/', views.home),
    path('exams/', views.exams),
    path('meds/', views.meds),
    path('cal/', views.cal),
    path('', views.Paciente.as_view(), name='paciente'),
    path('lista/', views.ListaPacientes.as_view(), name='lista'),
    path('crear', views.CrearPaciente.as_view(), name='crear'),
    path('<int:pk>/editar', views.EditarPaciente.as_view(), name='editar'),
    path('<int:pk>/eliminar', views.EliminarPaciente.as_view(), name='eliminar'),
]

medicina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls'))
]

app1/models.py
from django.db import models

# Create your models here.
class Pacientes(models.Model):
    run = models.CharField(max_length=9, primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    edad = models.IntegerField()

app1/forms.py
import datetime
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
'''
def validar_fecha(fecha):
    fecha_menor = datetime.datetime.strptime("1900-01-01", "%Y-%m-%d").date()
    fecha_mayor = datetime.datetime.strptime("2020-12-31", "%Y-%m-%d").date()
    if fecha_menor <= fecha <= fecha_mayor:
        return fecha
    else:
        raise ValidationError("Sólo fechas hasta diciembre 2020")

class FormularioRegistro(forms.Form):
    nombre = forms.CharField(initial="Nombre",
                    validators=[validators.MinLengthValidator(2, "Mínimo 2 letras")])
    apellido = forms.CharField(initial="Apellido",
                    validators=[validators.MinLengthValidator(2, "Mínimo 2 letras")])
    rut = forms.IntegerField(initial="Ingrese su RUT sin puntos ni dígito verificador")
    fecha_de_nacimiento = forms.DateField(validators=[validar_fecha])
    
    email = forms.EmailField(validators=[validators.EmailValidator])

    telefono = forms.IntegerField(initial="Ingrese un número de 9 dígitos",
                    validators= (9, "Ingrese un teléfono válido!!"))

from django import forms

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++
'''
from django import forms
from django.core.exceptions import ValidationError
from django.core import validators
import datetime

def validar_fecha(fecha):
    fecha_base = datetime.datetime.strptime("01-01-1920", "%d-%m-%Y").date()
    if fecha >= fecha_base:
        return fecha
    else:
        raise ValidationError("Sólo fechas mayores o iguales a 1920")

class RegistroPaciente(forms.Form):

    run = forms.CharField(
        label='R.U.N',
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder':'9.999.999-9'},
            ),
        validators=[validators.MaxLengthValidator(12,'Rut Incorrecto!'),
                validators.MinLengthValidator(11,'Rut Incorrecto')]
        )
    nombre = forms.CharField(
        label='Nombre',
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder':'Ingrese su nombre'})
        )
    apellido = forms.CharField(
        label='Apellido',
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder':'Ingrese su apellido'})
        )
    fecha_nacimiento = forms.DateField(
        label='Fecha de nacimiento',
        widget= forms.DateInput(attrs={
            'class': 'form-control',
            'type': 'date',
            'placeholder':'Año-Mes-Dia'}
            ),
        validators=[validar_fecha]
        )



class LoginForm(forms.Form):

    user = forms.CharField(
        label = 'Usuario',
        widget= forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Ingrese su Usuario'
        })
    )

    password = forms.CharField(
        label = 'Contraseña',
        widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder':'Ingrese su contraseña'
        })
    )

app1/views.py
from django.shortcuts import render, redirect
from .forms import RegistroPaciente, LoginForm
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.views import generic
from django.views.generic import ListView
from .models import Pacientes
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy



# Create your views here.
def inicio(request):
    return render(request, 'app1/index.html')

def home(request):
    return render(request, 'app1/main.html') 

def register(request):
    return render(request, 'app1/registro.html')  

def exams(request):
    return render(request, 'app1/examenes.html') 

def meds(request):
    return render(request, 'app1/medicamento.html')

def cal(request):
    return render( request, 'app1/calendario.html')

class Paciente(generic.TemplateView):
    template_name = 'app1/home.html'

class ListaPacientes(ListView):
    model=Pacientes
    template_name = 'app1/lista_pacientes.html'
    context_object_name = 'pacientes'

class CrearPaciente(CreateView):
    model=Pacientes
    template_name = 'app1/crear_paciente.html'
    fields='__all__'
    success_url= reverse_lazy('app1:lista')


class EditarPaciente(UpdateView):
    model=Paciente
    template_name = 'app1/editar_paciente.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista')


class EliminarPaciente(DeleteView):
    model=Paciente
    template_name = 'app1/eliminar_paciente.html'
    fields='__all__'
    success_url=reverse_lazy('app1:lista')
    context_object_name = 'paciente'
    

app1/templates/app1/crear_paciente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        <table border="1">
            {{form.as_table}}
        </table>
        <input type="submit" value="Guardar">
        <a href="{% url 'app1:lista' %}"><button type="button">Cancelar</button></a>
    </form>

</body>
</html>

app1/templates/app1/index.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
  <title>SINARS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Loading Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="css/style.css">
</head>

<body>
  <!-- Navigation Bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">SINARS</a>

    <!-- Navigation Bar Hamburger-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false"
      aria-controls="navigation" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- End Navigation Bar Hamburger -->
    <!-- Navigation Links -->
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">

        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
            aria-expanded="false">
            Login <span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            <form class="px-4 py-3">
              <div class="form-group">
                <label >Email</label>
                <input type="email" class="form-control" id="login-user" placeholder="email@xxx.com">
              </div>
              <div class="form-group">
                <label>Contraseña</label>
                <input type="password" class="form-control" id="login-pass" placeholder="Contraseña">
              </div>
              <div class="form-group">
                <div class="form-check">
                  <input type="checkbox" class="form-check-input" id="dropdownCheck">
                  <label class="form-check-label" for="dropdownCheck">
                    Recordar Datos
                  </label>
                </div>
              </div>
              <button type="button" class="btn btn-primary" onclick="login()">Ingresar</button>
            </form>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="registro.html">No está registrado? Regístrese aquí</a>
            <a class="dropdown-item" href="#">Olvidó su contraseña?</a>
          </div>
          <div class="dropdown-menu dropdown-menu-right">
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Buscar">
        <button class="btn btn-outline-success border-dark 
                    font-weight-bold text-white my-2 my-sm-0" type="submit">Buscar</button>
      </form>
    </div>
    <!-- Navigation Links -->
  </nav>
  <!-- End Navigation Bar -->

  <!-- Section: Principal -->
  <div class="jumbotron">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'img/coronavirus2.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/nurse.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'img/dpctpriiiiiiiiiiiiiiiiiiikkkkkkkkkkkkkj8.jpg' %}" class="d-block w-100" alt="50">
          <div class="carousel-caption d-none d-md-block">
            <h1>SINARS</h1>
            <p class="h2">Primer sistema de registro nacional de datos de salud de Chile</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <!-- End Section: Principal -->

  <!-- Section: Competencias -->
  <div class="container-fluid noticias">

    <div class="row">
      <h2>Noticias de Interés</h2>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Curso Cuidado Integral</h2>
          <div class="card-body">
            <h3 class="card-title">Inicio: 24 de Noviembre</h3>
            <p class="card-text">Curso semipresencial de 120 horas de duración que busca contribuir al fortalecimiento y
              puesta en práctica de los conocimientos, actitudes y habilidades relacionadas con el abordaje y manejo
              integral de los usuarios adultos mayores que se atienden en atención primaria.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Agenda País: Mes del Adulto Mayor</h2>
          <div class="card-body">
            <h3 class="card-title">Mes del Adulto Mayor</h3>
            <p class="card-text">Talleres, apoyo económico y programas de salud buscan potenciar el envejecimiento
              positivo.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Tendencias: La Risoterapia</h2>
          <div class="card-body">
            <h3 class="card-title">El mágico poder tonificante de la risa</h3>
            <p class="card-text">La risoterapia o terapia de risas aporta grandes beneficios en la salud física y
              emocional del adulto mayor, especialmente para afrontar los momentos de #soledad y depresión tan comunes
              en la vejez.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="card">
          <h2 class="card-header">Coronavirus en el Mundo</h2>
          <div class="card-body">
            <h3 class="card-title">¿Puede el covid-19 convertirse en un virus endémico?</h3>
            <p class="card-text">Todavía se desconoce mucho sobre la covid-19 y el virus que la causa, el SARS-Cov-2,
              pero como han mostrado otras infecciones en el pasado, es muy probable que este coronavirus continúe
              transmitiéndose, incluso si contamos con una vacuna.</p>
            <a href="#!" class="btn btn-dark">Ver mas</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Section: Competencias -->

  <!-- Section: Enlaces -->
  <div class="container-fluid bg-dark text-center">
    <div class="row">
      <h3>Enlaces de Interés</h3>
    </div>
    <div class="row">
      <div class="col-md-4">
          <a href="https://www.hospitaldigital.gob.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/logo-hospital-digital.png' %}" alt="..."> </a>
      </div>
      <div class="col-md-4">
        <a href="https://samu.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/Logo-SAMU-Metropolitano.png' %}" alt="..." > </a>
      </div>
      <div class="col-md-4">
        <a href="https://www.doctoralia.cl/"> <img class="img-fluid img-logo"  src="{% static 'img/logo-doctoralia.png' %}" alt="..." > </a>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <a href="https://www.fonasa.cl/sites/fonasa/inicio"> <img class="img-fluid img-logo"  src="{% static 'img/fonasa.png' %}" alt="..." > </a>
      </div>
      <div class="col-md-6">
       <a href="http://www.isapre.cl/home"> <img class="img-fluid img-logo"  src="{% static 'img/logoisapre.png' %}" alt="..." > </a>
      </div>
    </div>
  </div>


  <footer class="footer bg-dark text-center w-100">
    <p class="text-muted">&copy; 2020 Awakelab.</p>
    <p class="text-muted">Grupo Full Stack Python</p>
  </footer>

  <!-- jQuery, Popper.js, Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>

  <script src="{% static 'js/login.js' %}"></script>
</body>

</html>

app1/templates/app1/lista_pacientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Lista Pacientes</h1>
    <a href="{% url 'app1:crear' %}"> Agregar Paciente</a> 
    <table border="1px">
        <tr>
            <th>Run</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th></th>
            <th></th>
        </tr>
        {% for elemento in paciente %}
        <tr>
            <th>{{ elemento.run }}</th>
            <th>{{ elemento.nombre }}</th>
            <th>{{ elemento.apellido }}</th>
            <th>{{ elemento.edad }}</th>
            <th><a href="{% url 'app1:editar' pk=elemento.run %}">Editar</a></th>
            <th><a href="{% url 'app1:eliminar' pk=elemento.run %}">Eliminar</a></th>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

app1/templates/app1/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Admin</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        body{
            background-color: grey;
        }

        .mt-18{
            margin-top: 180px;
        }

        .login-card{
            background-color: whitesmoke;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-center mt-18" ">
            <div class="col-sm-4 p-3 login-card ">
                
                <form action=""  method="post">
                    {% csrf_token %}
                    {{ msg }}
                    {{login_form.as_table}}
                    <br>
                    <input class="btn btn-primary btn-block" type="submit" value="Entrar">
                </form>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app1/templates/app1/main.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
  <title>Usuario</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Loading Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style-nav.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-custom flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">SINARS - Bienvenida Julianne Moore</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
        data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="index.html">Logout</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light pt-4 sidebar collapse">
          <div class="sidebar-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="main.html">
                  <span data-feather="home"></span>
                  <h4>Home</h4>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="examenes.html">
                  
                  <h4>Exámenes</h4>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="medicamento.html">
                  <h4>Medicamentos</h4>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="calendario.html">
                  <h4>Calendario</h4>
                </a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      <div class="col-md-10 ml-auto">
        <div class="card mb-3">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="{% static 'img/julianne-moore.jpg' %}" class="card-img img-fluid" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h3 class="card-title">Julianne Moore</h3>
                <p class="h4"><small class="text-muted">RUT:</small>
                  13.781.999-3</p>
                <p class="h4"><small class="text-muted">FECHA DE NACIMIENTO</small>
                  03/12/1960</p>
                <p class="h4"><small class="text-muted">EDAD:</small>
                  59 años</p>
                <br>
                <h3 class="card-title">Datos de Contacto</h3>
                <p class="h4"><small class="text-muted">DIRECCIÓN:</small>
                  Av El Bosque 5.678, Providencia</p>
                <p class="h4"><small class="text-muted">EMAIL:</small>
                  julianne.moore@gmail.com</p>
                <p class="h4"><small class="text-muted">TELÉFONO:</small>
                  (+56 9) 9234 5678</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 patologia">
            <div class="card">
              <h2 class="card-header">Patologías Asociadas</h2>
              <div class="card-body">
                <ul>
                  <li>
                    <p class="h5">Resistencia a la Insulina</p>
                  </li>
                  <li>
                    <p class="h5">Hipertensión</p>
                  </li>
                  <li>
                    <p class="h5">Hipertiroidismo</p>
                  </li>
                  <li>
                    <p class="h5">Artritis Reumatoide</p>
                  </li>
                  <li>
                    <p class="h5">Osteoporosis en Estudio</p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <br>
      </div>
    </div>
  
    <!-- End Section: Principal -->

    <footer class="text-center" style="height: 100px; background-color: black;">

      <p style="padding-top: 30px; text-decoration-color: white;">Full Stack Python 154-1 - Grupo 2</p>

  </footer>

    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
      </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
      </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
      </script>
  </body>

</html>

app1/templates/app1/pacientes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registros</title>
</head>
<body>
    <h1>PACIENTES</h1>
    {% for paciente in pacientes %}
        <p>{{paciente}}</p>
    {% endfor %}
</body>
</html>